name: Code Quality & Security

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  quality-check:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: TypeScript Compilation Check
      run: npx tsc --noEmit --skipLibCheck

    - name: Playwright Config Validation
      run: npx playwright test --list > /dev/null

    - name: Check for sensitive data
      run: |
        # Check for potential secrets or sensitive data
        if grep -r -i -E "(password|secret|key|token)" --include="*.ts" --include="*.js" --include="*.json" . --exclude-dir=node_modules; then
          echo "⚠️ Warning: Potential sensitive data found in code"
          exit 1
        else
          echo "✅ No sensitive data patterns detected"
        fi

    - name: Validate test data
      run: |
        # Validate JSON fixtures
        for file in tests/fixtures/*.json; do
          if [ -f "$file" ]; then
            echo "Validating $file"
            node -e "JSON.parse(require('fs').readFileSync('$file', 'utf8'))"
          fi
        done

  dependency-check:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Check for security vulnerabilities
      run: npm audit --audit-level=moderate

    - name: Check for outdated packages
      run: npm outdated || true

    - name: License compliance check
      run: |
        echo "Checking license compliance..."
        npx license-checker --summary || echo "License checker not available, skipping..."
