name: Playwright Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  schedule:
    # Run tests daily at 2 AM UTC
    - cron: '0 2 * * *'
  workflow_dispatch:
    # Allow manual trigger

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Test on multiple Node.js versions
        node-version: [18.x, 20.x]
        # Test different browsers
        browser: [chromium, firefox, webkit]
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps ${{ matrix.browser }}

    - name: Run Playwright tests on ${{ matrix.browser }}
      run: npx playwright test --project=${{ matrix.browser }}
      env:
        CI: true

    - name: Upload Playwright Report
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: playwright-report-${{ matrix.browser }}-node${{ matrix.node-version }}
        path: playwright-report/
        retention-days: 30

    - name: Upload Test Results
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: test-results-${{ matrix.browser }}-node${{ matrix.node-version }}
        path: test-results/
        retention-days: 30

  # Job for running all tests together (for comprehensive reporting)
  test-all:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    needs: test
    if: always()
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Install all Playwright Browsers
      run: npx playwright install --with-deps

    - name: Run all Playwright tests
      run: npx playwright test
      env:
        CI: true

    - name: Generate and upload HTML report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report-all-browsers
        path: playwright-report/
        retention-days: 30

    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results-all-browsers
        path: test-results/
        retention-days: 30

  # Job for publishing test results as GitHub Pages (optional)
  publish-report:
    name: Publish HTML Report
    runs-on: ubuntu-latest
    needs: test-all
    if: always()
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    steps:
    - name: Setup Pages
      uses: actions/configure-pages@v4
      
    - name: Download test report
      uses: actions/download-artifact@v4
      with:
        name: playwright-report-all-browsers
        path: playwright-report/
        
    - name: Upload to GitHub Pages
      uses: actions/upload-pages-artifact@v3
      with:
        path: playwright-report/
        
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
